name: Bug Report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report and help us improve! :)
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: gget version
      description: Which version of gget are you using?
      placeholder: 0.27.2
    validations:
      required: true
  - type: dropdown
    id: interface
    attributes:
      label: User interface
      description: Did the problem occur when calling gget from the command-line or Python? (Select all that apply.)
      multiple: true
      options:
        - Command-line
        - Python
        - Google Colab (please include a shareable link if possible)
        - R (please specify Python wrapper)
        - Not applicable
    validations:
      required: true
  - type: textarea
    id: command
    attributes:
      label: What is the exact command that was run?
      description: Please copy-paste the gget command that caused the problem. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: command-output
    attributes:
      label: Which output/error did you get?
      description: Please copy-paste the complete output/error returned by the command entered above.
      render: shell
